[workspace]
members = ["logic"]
exclude = ["tools/render-assets"]

[package]
name = "plenty-of-fish-in-the-sea"
version = "0.0.0"
edition = "2021"
description = "Our Game-Off 2022 game jam participation"


[dependencies]
good-web-game = "0.6.0"
logic = {path = "logic"}

num-rational = {version = "0.4"}

[build-dependencies]
tar = "0.4"
built = { version = "0.5", features = ["git2", "chrono"] }


[profile.release]
strip = true
lto = true
panic = 'abort'
codegen-units = 1
opt-level = 'z'
