name: Deploy to Itch.io

on:
  # the 1st condition
  workflow_run:
    workflows: ["Rust"]
    tags: [ "v*" ]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ITCH_USERNAME: coffejunkstudio
  ITCH_GAME_ID: plenty-of-fish-in-the-sea
jobs:
  deploy-web:
    name: Upload web-package to Itch
    runs-on: ubuntu-latest
    environment: itchio

    steps:
      - name: Fetch web package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: rust.yml
          workflow_conclusion: success
          name: web-package
          path: '.'
      - name: Upload artifact
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: "."
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: web-stable
          buildNumber: ${{ github.ref_name }}

  deploy-linux:
    name: Upload web-package to Itch
    runs-on: ubuntu-latest
    environment: itchio

    steps:
      - name: Fetch web package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: rust.yml
          workflow_conclusion: success
          name: linux
          path: '.'
      - name: Upload artifact
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: "."
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: linux-stable
          buildNumber: ${{ github.ref_name }}

  deploy-windows:
    name: Upload web-package to Itch
    runs-on: ubuntu-latest
    environment: itchio

    steps:
      - name: Fetch web package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: rust.yml
          workflow_conclusion: success
          name: windows
          path: '.'
      - name: Upload artifact
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: "."
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: windows-stable
          buildNumber: ${{ github.ref_name }}
