name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prep
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libasound2-dev libudev-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  native:
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
    - uses: actions/checkout@v3
    - name: prep
      run: apt-get update && apt-get install -y --no-install-recommends libasound2-dev libudev-dev
    - name: Build binary
      run: cargo build --release --verbose
    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: linux-native
        path: target/release/plenty-of-fish-in-the-sea

  web:
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
    - uses: actions/checkout@v3
    - name: target
      run: rustup target add wasm32-unknown-unknown
    - name: Build binary
      run: bash build-web.sh --release
    - name: Archive web
      uses: actions/upload-artifact@v3
      with:
        name: web-package
        path: target/web-pkg
